// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('PassGenTest', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('PassGenTest', async function() {
    await driver.get("https://elias-espinheira.github.io/PasswordGenerator/")
    await driver.manage().window().setRect({ width: 734, height: 700 })
    await driver.findElement(By.id("button")).click()
    await driver.findElement(By.id("password")).click()
    assert(await driver.switchTo().alert().getText() == "Senha copiada com sucesso!")
    await driver.findElement(By.id("slider")).sendKeys("19")
    await driver.findElement(By.id("slider")).click()
    await driver.findElement(By.id("button")).click()
    await driver.findElement(By.id("password")).click()
    assert(await driver.switchTo().alert().getText() == "Senha copiada com sucesso!")
    assert(await driver.getTitle() == "Gerador de senha")
    await driver.close()
  })
})
